%Lista de preguntas
caracteristicas([
'tiene bloques tipo C: {}',
'admite programacion orientada a objetos (POO)',
'tiene muuuuchos parentesis (((())))',
'tiene muuuuuchas listas ((())) o [[[]]]',
'admite la programacion funcional, o referenciar a una funcion por su direccion de memoria',
'admite el paradigma de programacion logico',
'fue creado en el siglo XXI',
'es utilizado oficialmente por Microsoft',
'es utilizado oficialmente por Apple',
'es compilado',
'es interpretado',
'es de alto nivel, en general no tiene acceso a punteros ni a registros',
'es de bajo nivel, en general si tiene acceso a punteros o a registros',
'esta incluido en el kernell de Linux',
'soporta la libreria std',
'esta pensado para consultar bases de datos',
'es un lenguaje imperativo, tiene asignacion de variables y funciones',
'es un lenguaje de marcaje basado en tags',
'es un lenguaje orientado a web',
'es un lenguaje pensado para representar estructuras de datos (datos organizados)',
'es ejecutado por un navegador',
'es utilizado de forma oficial por Google',
'es utilizado de forma oficial por Mozilla',
'es utilizado de forma oficial por Oracle',
'es ejecutado por la JMV',
'es ejecutable por Android de forma nativa',
'es ejecutable por iOS de forma nativa',
'tiene muuuuchos angulos <<<<>>>>',
'soporta la libreria Tensorflow',
'soporta la libreria OpenCV',
'es utilizado profesionalmente para crear videojuegos',
'es utilizado por NVidia para programar CUDA',
'tiene sus sentencias terminadas en ; ',
'tiene un tipado fuerte en sus variables',
'tiene tipado dinamico en sus variables',
'tiene autotipado en sus variables',
'soporta lazzy memory',
'tiene punteros',
'tiene recolector de basura',
'tiene concurrencia basada en agentes',
'es un lenguaje transaccional',
'admite la sentencia GOTO',
'fue disenado para manejar texto y archivos']).