
o(1, [el,hombre,grande,come,la,manzana,roja]).
o(2, [el,hombre,con,un,tenedor,grande,come,la,manzana,roja]).
o(3, [juan,y,maria,comen,la,manzana,roja,con,un,tenedor,y,un,cuchillo]).
o(4, [ella,hace,la,practica,de,juan]).
o(5, [el,canario,de,juan,y,maria,canta]).
o(6, [la,blanca,paloma,alzo,el,vuelo]).
o(7, [esta,muy,lejos,de,madrid]).
o(8, [el,es,lento,de,reflejos]).
o(9, [juan,habla,muy,claramente]).
o(10, [la,esperanza,de,vida,de,un,nino,depende,de,su,lugar,de,nacimiento]).
o(11, [el,hombre,que,vimos,en,la,universidad,era,mi,profesor]).
o(12, [juan,que,es,muy,delicado,come,solamente,manzanas,rojas]).
o(13, [el,procesador,de,textos,que,es,una,herramienta,muy,potente,sirve,para,escribir,documentos]).
o(14, [juan,es,moreno,y,maria,es,alta]).
o(15, [juan,recoge,la,mesa,mientras,maria,toma,un,cafe]).
o(16, [compre,un,pantalon,y,una,corbata,negros]).
o(17, [juan,y,hector,comen,patatas,fritas,y,beben,cerveza]).
o(18, [irene,canta,y,salta,mientras,juan,estudia]).
o(19, [irene,canta,y,salta,y,sonrie,alegre]).
o(20, [el,procesador,de,textos,es,una,herramienta,muy,potente,que,sirve,para,escribir,documentos,pero,es,bastante,lento]).
o(21, [el,hombre,come,una,manzana]).
o(22, [la,mujer,come,manzanas]).
o(23, [maria,come,una,manzana,roja]).
o(24, [juan,ama,a,maria]).
o(25, [el,gato,grande,come,un,raton,gris]).
o(26, [juan,estudia,en,la,universidad]).
o(27, [el,alumno,ama,la,universidad]).
o(28, [el,alumno,come,ratones]).
o(29, [el,raton,que,cazo,el,gato,era,gris]).
o(30, [la,universidad,es,grande]).

o(31, [el,hombre,grande,comen,la,manzana,roja]).